---
title: "Data_analysis_Group_3.3"
author: "Carina, Maike, Marcel, Mirja"
date: "20 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
title: "Data_analysis_2022_group_3.3"
author: "Carina, Maike, Marcel, Mirja"
date: "20 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the data
Raw_data <- read.table("C:\\Users\\Mirja\\Documents\\4. Semester\\Bioinfo\\RDeeP_HeLa_Interphase.csv", header=TRUE, row.names=1, sep = ";")
First <- Raw_data[1:10,]
First #first 10 rows
```
```{r}
#Dimension and Class
dim(Raw_data)
class(Raw_data)
range(Raw_data)
```

```{r}
#Col and Rownames 
colnames(Raw_data) # Fractions
rownames(First) # Proteinnames
```

```{r}
#reorganise the coulums
# if necessary install.packages("tidyverse")
library(tidyverse)
# Controll
HeLa_Ctrl = Raw_data %>% select(contains("Ctrl")) 
HeLa_Ctrl1 = HeLa_Ctrl %>% select(contains("Rep1"))
HeLa_Ctrl2 = HeLa_Ctrl %>% select(contains("Rep2"))
HeLa_Ctrl3 = HeLa_Ctrl %>% select(contains("Rep3"))

# RNAse
HeLa_RNAse = Raw_data %>% select(contains("RNA"))
HeLa_ordered = data.frame(HeLa_Ctrl, HeLa_RNAse)
HeLa_RNAse1 = HeLa_RNAse %>% select(contains("Rep1"))
HeLa_RNAse2 = HeLa_RNAse %>% select(contains("Rep2"))
HeLa_RNAse3 = HeLa_RNAse %>% select(contains("Rep3"))

```

```{r}
which(rowMeans(Raw_data) == 0) #nur eine Zeile ohne Werte
which(rowMeans(HeLa_RNAse) == 0)
which(rowMeans(HeLa_Ctrl) == 0)
````