---
title: "Project3.3"
author: "Simon"
date: "3 5 2022"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Testing basics

```{r}
#load the data
Raw_data <- read.table("C:\\Users\\Mirja\\Documents\\4. Semester\\Bioinfo\\RDeeP_HeLa_Interphase.csv", header=TRUE, row.names=1, sep = ";")
First <- Raw_data[1:10,]
First #first 10 rows
```

```{r}
#Dimension and Class
dim(Raw_data)
class(Raw_data)
range(MS_Table)
```

```{r}
#Col and Rownames 
colnames(MS_Table) # Fractions
rownames(First) # Proteinnames
```

```{r}
#Rowmeans
rowMeans(First)
which(rowMeans(MS_Table) == 0) #nur eine Zeile ohne Werte

```
```{r}
#colmeans 
which(colMeans(MS_Table) == 0)
```

```{r}
# 0 zu NA 
First[First == 0] <- NA
summary(First)
First
Data_NA = MS_Table[MS_Table == 0] <- NA
```
```{r}
#something like fraction
HeLa_Fractions  <- Raw_data[- trash, ]


Fraction1_Ctrl <- HeLa_Fractions[,1:3]
Fraction1_RNAse <- HeLa_Fractions[,4:6]
Fraction2_Ctrl <- HeLa_Fractions[,7:9]
Fraction2_RNAse <- HeLa_Fractions[,10:12]
Fraction3_Ctrl <- HeLa_Fractions[,13:15]
Fraction3_RNAse <- HeLa_Fractions[,16:18]
Fraction4_Ctrl <- HeLa_Fractions[,19:21]
Fraction4_RNAse <- HeLa_Fractions[,22:24]
Fraction5_Ctrl <- HeLa_Fractions[,25:27]
Fraction6_RNAse <- HeLa_Fractions[,28:30]
Fraction6_Ctrl <- HeLa_Fractions[,31:33]
Fraction7_RNAse <- HeLa_Fractions[,34:36]
Fraction7_Ctrl <- HeLa_Fractions[,37:39]
Fraction14_RNAse <- HeLa_Fractions[,40:42]
Fraction15_Ctrl <- HeLa_Fractions[,43:45]
Fraction16_RNAse <- HeLa_Fractions[,46:48]
Fraction17_Ctrl <- HeLa_Fractions[,49:51]
Fraction18_RNAse <- HeLa_Fractions[,52:54]
Fraction19_Ctrl <- HeLa_Fractions[,55:57]
Fraction20_RNAse <- HeLa_Fractions[,58:60]
Fraction21_Ctrl <- HeLa_Fractions[,61:63]
Fraction22_RNAse <- HeLa_Fractions[,64:66]
Fraction23_Ctrl <- HeLa_Fractions[,67:69]
Fraction24_RNAse <- HeLa_Fractions[,70:72]
Fraction25_Ctrl <- HeLa_Fractions[,73:75]
````


```{r}
#new range
min (MS_Table, na.rm = TRUE)
max(MS_Table, na.rm = TRUE)

```

```{r}
#reorganise the coulums
# if necessary install.packages("tidyverse")
library(tidyverse)
# Controll
HeLa_Ctrl = MS_Table %>% select(contains("Ctrl")) 
HeLa_Ctrl1 = HeLa_Ctrl %>% select(contains("Rep1"))
HeLa_Ctrl2 = HeLa_Ctrl %>% select(contains("Rep2"))
HeLa_Ctrl3 = HeLa_Ctrl %>% select(contains("Rep3"))

# RNAse
HeLa_RNAse = MS_Table %>% select(contains("RNA"))
HeLa_ordered = data.frame(HeLa_Ctrl, HeLa_RNAse)
HeLa_RNAse1 = HeLa_RNAse %>% select(contains("Rep1"))
HeLa_RNAse2 = HeLa_RNAse %>% select(contains("Rep2"))
HeLa_RNAse3 = HeLa_RNAse %>% select(contains("Rep3"))

```

```{r}
range(HeLa_Ctrl, na.rm = TRUE)

range(HeLa_RNAse, na.rm = TRUE)
``` 

```{r}
# Indices
indices <-c(1:25)

# Plot first protein in DataFrame

plot(x = indices, y = HeLa_Ctrl1[1,], type = 'l', col = 'darkgreen')
  lines(x = indices, y = HeLa_RNAse1 [1,], type = 'l', col = 'red')
  legend(x = "topright",                      # Position
       legend = c("ctrl", "RNase"),           # Legend texts
       col = c('darkgreen', 'red'),           # Line colors
       lwd = 2)                               # Line width
```

```{r}
# Plot first ten proteins in DataFrame

for(i in c(1:10)) {
  plot(x = indices, y = HeLa_Ctrl1[i,], type = 'l', col = 'darkgreen')
  lines(x = indices, y = HeLa_RNAse1[i,], type = 'l', col = 'red')
  legend(x = "topright",
       legend = c("ctrl", "RNase"),
       col = c('darkgreen', 'red'),
       lwd = 2)                   
}
```

--> Within the first ten there appears to be no shifting protein as the curves seem almost identical upon first glance


## Plotting a "sure" shift protein

```{r}
plot(x = indices, y = HeLa_Ctrl1["SIN3A",], type = 'l', col = 'darkgreen')
  lines(x = indices, y = HeLa_RNAse1["SIN3A",], type = 'l', col = 'red')
  legend(x = "topright",                      
       legend = c("ctrl", "RNase"),         
       col = c('darkgreen', 'red'),           
       lwd = 2)                              
```
--> Shift is visible, although quite wonky ;)
--> It becomes evident that normalization is needed (compare Fig 3 Maiwen Molecular Cell)!

```{r}
which(colMeans(HeLa_RNAse) == 0)
which(colMeans(HeLa_Ctrl) == 0)
````
## Dataset with Na safe with different name otherwise named integer